spring.application.name=hand-gesture-recognition

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hand_gesture_db
spring.datasource.username=postgres
spring.datasource.password=your db password

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080